# Use Node.js LTS
FROM node:22

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci

# Copy all frontend files
COPY . .

# Build the Next.js application
RUN npm run build


WORKDIR /app


# Expose the port Next.js runs on
EXPOSE 3000

# Start the Next.js application
CMD ["npm", "start"]