import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navbar } from "./__components/__navbar";
import { Sidebar } from "./__components/__sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased overflow-x-hidden">
        <div className="flex flex-col h-screen overflow-x-hidden">
          <div className="flex flex-1 overflow-hidden">
            <Sidebar />
            <main className="flex-1 overflow-y-auto bg-[#e5e5e5] p-4">
              <Navbar />
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
