version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"  # Keep frontend on port 3000
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000  # Updated to match backend's internal port
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"  # Changed external port to 8000 to avoid conflict
    environment:
      - NODE_ENV=production
    env_file:
      - .env 
    networks:
      - app-network
    volumes:
      - /app/node_modules
 
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "9000:9000" # Public TCP port for tracker
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge