# Use Node.js LTS
FROM node:22

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy source files
COPY . .

# Build the application
RUN npx prisma generate
RUN npm run build

EXPOSE 3001

# Start the NestJS application
CMD ["node", "dist/main"]